package com.janmee.spider.entity;

import com.alibaba.fastjson.annotation.JSONField;
import com.alibaba.fastjson.annotation.JSONType;

public class Stock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.id
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.name
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    private String name = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.cname
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    private String cname = "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.category
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    private String category= "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.category_id
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    @JSONField(name = "category_id")
    private String categoryId= "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.symbol
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    private String symbol= "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.mktcap
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    private String mktcap= "";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.pe
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    private Float pe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock.market
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    private String market= "";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.id
     *
     * @return the value of stock.id
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.id
     *
     * @param id the value for stock.id
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.name
     *
     * @return the value of stock.name
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.name
     *
     * @param name the value for stock.name
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.cname
     *
     * @return the value of stock.cname
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.cname
     *
     * @param cname the value for stock.cname
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.category
     *
     * @return the value of stock.category
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.category
     *
     * @param category the value for stock.category
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public void setCategory(String category) {
        if (category == null)this.category = "";
        else this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.category_id
     *
     * @return the value of stock.category_id
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.category_id
     *
     * @param categoryId the value for stock.category_id
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.symbol
     *
     * @return the value of stock.symbol
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.symbol
     *
     * @param symbol the value for stock.symbol
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.mktcap
     *
     * @return the value of stock.mktcap
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public String getMktcap() {
        return mktcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.mktcap
     *
     * @param mktcap the value for stock.mktcap
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public void setMktcap(String mktcap) {
        this.mktcap = mktcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.pe
     *
     * @return the value of stock.pe
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public Float getPe() {
        return pe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.pe
     *
     * @param pe the value for stock.pe
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public void setPe(Float pe) {
        this.pe = pe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock.market
     *
     * @return the value of stock.market
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock.market
     *
     * @param market the value for stock.market
     *
     * @mbggenerated Sat Apr 23 11:39:26 CST 2016
     */
    public void setMarket(String market) {
        this.market = market;
    }
}