package com.janmee.spider.entity;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class StockDaily {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_daily.id
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_daily.stock_id
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    private Integer stockId;

    private String stockCname;

    private String stockSymbol;

    public String getStockCname() {
        return stockCname;
    }

    public void setStockCname(String stockCname) {
        this.stockCname = stockCname;
    }

    public String getStockSymbol() {
        return stockSymbol;
    }

    public void setStockSymbol(String stockSymbol) {
        this.stockSymbol = stockSymbol;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_daily.date
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    @JSONField(name = "d")
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_daily.open
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    @JSONField(name = "o")
    private Double open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_daily.high
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    @JSONField(name = "h")
    private Double high;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_daily.low
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    @JSONField(name = "l")
    private Double low;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_daily.current
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    @JSONField(name = "c")
    private Double current;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_daily.volume
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    @JSONField(name = "v")
    private Long volume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_daily.id
     *
     * @return the value of stock_daily.id
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_daily.id
     *
     * @param id the value for stock_daily.id
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_daily.stock_id
     *
     * @return the value of stock_daily.stock_id
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public Integer getStockId() {
        return stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_daily.stock_id
     *
     * @param stockId the value for stock_daily.stock_id
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public void setStockId(Integer stockId) {
        this.stockId = stockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_daily.date
     *
     * @return the value of stock_daily.date
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_daily.date
     *
     * @param date the value for stock_daily.date
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_daily.open
     *
     * @return the value of stock_daily.open
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public Double getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_daily.open
     *
     * @param open the value for stock_daily.open
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public void setOpen(Double open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_daily.high
     *
     * @return the value of stock_daily.high
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public Double getHigh() {
        return high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_daily.high
     *
     * @param high the value for stock_daily.high
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public void setHigh(Double high) {
        this.high = high;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_daily.low
     *
     * @return the value of stock_daily.low
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public Double getLow() {
        return low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_daily.low
     *
     * @param low the value for stock_daily.low
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public void setLow(Double low) {
        this.low = low;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_daily.current
     *
     * @return the value of stock_daily.current
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public Double getCurrent() {
        return current;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_daily.current
     *
     * @param current the value for stock_daily.current
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public void setCurrent(Double current) {
        this.current = current;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_daily.volume
     *
     * @return the value of stock_daily.volume
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public Long getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_daily.volume
     *
     * @param volume the value for stock_daily.volume
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    public void setVolume(Long volume) {
        this.volume = volume;
    }
}