package com.janmee.spider.dao;

import com.janmee.spider.entity.StockDaily;

import java.util.List;
import java.util.Date;

public interface StockDailyDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_daily
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_daily
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    int insert(StockDaily record);

    int insertBatch(List<StockDaily> stockDailies);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_daily
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    int insertSelective(StockDaily record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_daily
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    StockDaily selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_daily
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    int updateByPrimaryKeySelective(StockDaily record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_daily
     *
     * @mbggenerated Sun Apr 24 14:35:10 CST 2016
     */
    int updateByPrimaryKey(StockDaily record);

    Date selectLastestDay(String symbol);
}