package com.janmee.spider.dao;

import com.janmee.spider.entity.Stock;

import java.util.List;

public interface StockDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Sat Apr 23 11:25:30 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Sat Apr 23 11:25:30 CST 2016
     */
    int insert(Stock record);

    int insertBatch(List<Stock> stocks);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Sat Apr 23 11:25:30 CST 2016
     */
    int insertSelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Sat Apr 23 11:25:30 CST 2016
     */
    Stock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Sat Apr 23 11:25:30 CST 2016
     */
    int updateByPrimaryKeySelective(Stock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock
     *
     * @mbggenerated Sat Apr 23 11:25:30 CST 2016
     */
    int updateByPrimaryKey(Stock record);

    List<Stock> selectAll();

    List<Stock> selectNotExist();

    Stock selectBySymbol(String symbol);
}